const Colors = {
  verylightgray: '#C8C8C8',
  green: '#7ED957',
  black: '#000',
  white: '#fff',
  gray: '#7F7F7F',
  wild: '#4F3422',
  lightgray: '#CDCDCD',
  purple: '#7140A1',
  blue: '#034FAF',
  brownpod: '#202244',
  red: '#E31B25',
  inactive: '#A4BE99',
  bback: '#F7F4F2',
  header: '#424242',
};
const fonts = {
  BOLD: 'MerriweatherSans-Bold',
  REGULAR: 'MerriweatherSans-Regular',
  EXTRABOLD: 'MerriweatherSans-ExtraBold',
  LIGHT: 'MerriweatherSans-Light',
  LIGHT: 'MerriweatherSans-Light',
};
const images = {
  background1: require('../assets/Images/back1.png'),
  background: require('../assets/Images/back.png'),
  avatar: require('../assets/Images/avatar.png'),
  onb: require('../assets/Images/onb.png'),
  onb1: require('../assets/Images/onb1.png'),
  onb2: require('../assets/Images/onb2.png'),
  onb4: require('../assets/Images/onb4.png'),
  onboarding1: require('../assets/Images/onboarding1.png'),
  onboarding2: require('../assets/Images/onboarding2.png'),
  onboarding3: require('../assets/Images/onboarding3.png'),
  main: require('../assets/Images/main.png'),
  damage: require('../assets/Images/damage.png'),
  bumper: require('../assets/Images/bumper.png'),
  watch: require('../assets/Images/watch.png'),
  thankyou: require('../assets/Images/thankyou.png'),
  profileback: require('../assets/Images/profileback.png'),
  repair: require('../assets/Images/repair.png'),
  upcoming: require('../assets/Images/upcoming.png'),
  cleaning: require('../assets/Images/cleaning.jpg'),
  clean1: require('../assets/Images/clean1.png'),
  clean2: require('../assets/Images/clean2.png'),
  clean3: require('../assets/Images/clean3.png'),
  clean4: require('../assets/Images/clean4.png'),
  change: require('../assets/Images/change.png'),
  nonoti: require('../assets/Images/nonoti.png'),
  noproperty: require('../assets/Images/noproperty.png'),
  profile: require('../assets/Images/profile.jpg'),
  selectback: require('../assets/Images/selectback.jpg'),
  pdf: require('../assets/Images/pdf.png'),
  upload: require('../assets/Images/upload.png'),

  //noproperty   nonoti   invoice
};

const icons = {
  invoice: require('../assets/Icons/invoice.png'),
  user: require('../assets/Icons/user.png'),
  partner: require('../assets/Icons/partner.png'),
  logo: require('../assets/Icons/logo.png'),
  profile: require('../assets/Icons/profile.png'),
  lock: require('../assets/Icons/lock.png'),
  mobile: require('../assets/Icons/mobile.png'),
  email: require('../assets/Icons/email.png'),
  address: require('../assets/Icons/address.png'),
  appointment: require('../assets/Icons/appointment.png'),
  appointmentactive: require('../assets/Icons/appointmentactive.png'),
  homeactive: require('../assets/Icons/homeactive.png'),
  notification: require('../assets/Icons/notification.png'),
  notificationactive: require('../assets/Icons/notificationactive.png'),
  home: require('../assets/Icons/home.png'),
  bucket: require('../assets/Icons/bucket.png'),
  medium: require('../assets/Icons/medium.png'),
  minor: require('../assets/Icons/minor.png'),
  several: require('../assets/Icons/several.png'),
  add: require('../assets/Icons/add.png'),
  calender: require('../assets/Icons/calender.png'),
  clock: require('../assets/Icons/clock.png'),
  tick: require('../assets/Icons/tick.png'),
  Alert: require('../assets/Icons/Alert.png'),
  edit: require('../assets/Icons/edit.png'),
  logout: require('../assets/Icons/logout.png'),
  schedule: require('../assets/Icons/schedule.png'),
  acc: require('../assets/Icons/acc.png'),
  noimages: require('../assets/Icons/noimages.png'),
  arrow: require('../assets/Icons/arrow.png'),
  data: require('../assets/Icons/data.png'),
  new: require('../assets/Icons/new.png'),
  carsno: require('../assets/Icons/carsno.png'),
};

export {images, fonts, icons, Colors};
